SportStore/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SportStoreDal.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SportStore.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private ShoppingCart shoppingCart;

        public CartSummaryViewComponent(ShoppingCart cartService)
        {
            shoppingCart = cartService;
        }

        public IViewComponentResult Invoke()
        {
            return View(shoppingCart);
        }
    }
}

SportStore/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SportStoreDal.DataAccess;
using SportStoreDal.Models;
using SportStore.Infrastructure;
using SportStoreDal.Models.ViewModels;
using Microsoft.EntityFrameworkCore;
using SportStore.Models.ViewModels;

namespace SportStore.Controllers
{
    public class ShoppingCartController : Controller
    {
        private readonly StoreContext _context;
        private ShoppingCart shoppingCart;

        public ShoppingCartController(StoreContext context, ShoppingCart cartService)
        {
            _context = context;
            shoppingCart = cartService;
        }

        public ViewResult Index()
        {
            return View(new ShoppingCartIndexViewModel
            {
                ShoppingCart = shoppingCart,

            });
        }

        public RedirectToActionResult AddToShoppingCart(int productId)
        {
            ProductViewModel product = _context.Products.Select(p =>
            new ProductViewModel {
                Name = p.Name,
                ProductId = p.ProductId,
                UnitCost = p.UnitCost
            })
            .FirstOrDefault(p => p.ProductId == productId);

            if(product != null)
            {
                shoppingCart.AddItem(product, 1); 
            }

            return RedirectToAction("Index");
        }

        public RedirectToActionResult RemoveFromShoppingCart(int productId)
        {
            Product product = _context.Products
                              .FirstOrDefault(p => p.ProductId == productId);

            if (product != null)
            {
                shoppingCart.RemoveRecord(product.ProductId);             
            }
            return RedirectToAction("Index");

        }

        private ShoppingCart GetCart()
        {
            ShoppingCart cart = HttpContext.Session.GetJson<ShoppingCart>("Cart") ?? new ShoppingCart();
            return cart;
        }

        private void SaveCart(ShoppingCart cart)
        {
            HttpContext.Session.SetJson("Cart", cart);
        }

    }
}

SportStore/Views/Shared/ProductSummary.cshtml
@model ProductViewModel


    <div class="card card-outline-primary m-1 p-1">
        <div class="bg-light p-1">
            <h4>
                @Model.Name
                <span class="badge badge-pill badge-primary" style="float:right">
                    <small>@Model.UnitCost.ToString("c")</small>
                </span>
            </h4>
        </div>


        <form id="@Model.ProductId" asp-action="AddToShoppingCart" asp-controller="ShoppingCart" method="post">
            <input type="hidden" asp-for="ProductId" />
            <span class="card-text p-1">
                @Model.Description
                <button type="submit"
                        class="btn btn-success btn-sm pull-right" style="float:right">
                    Dodaj do koszyka
                </button>
            </span>
        </form>
    </div>

SportStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SportStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/libman.json">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <a class="navbar-brand" href="#">Sklep sportowy</a>
            <div class="col-10 text-right">
                @await Component.InvokeAsync("CartSummary")
            </div>
        </nav>
    </header>
    <div class="row m-1 p-1">
        <div id="categories" class="col-2">
            @await Component.InvokeAsync("NavigationMenu")
        </div>
        <div class="col-10">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - SklepSportowy <a asp-area="" asp-controller="Home"/>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>